import { useRef } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Header, Footer } from '../../shared/component/index';

function LoginForm() {
  const emailInput = useRef();
  const passwordInput = useRef();
  const SignIn = (e) => {
    e.preventDefault();
    // console.log('logged');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>WebPulse | Login Page</title>
      </Head>
      <div className="custom-background-vision"></div>
      <Header />
      <main className="mt-20">
        <section className="py-20">
          <div className="mx-auto max-w-6xl px-4">
            {/* card */}
            <div className="md:shadow mx-auto max-w-[460px] mt-12">
              {/* card-body */}
              <div className="px-10 py-20 border shadow-lg">
                <h2 className="text-center mb-5 text-2xl typo-playfair font-bold">
                  Sign in to webPulse
                </h2>
                <div className="mb-4">
                  <input
                    ref={emailInput}
                    type="email"
                    className={`w-full border outline-0 border-gray-600`}
                  />
                  <label htmlFor="email">Email</label>
                  {/* {isValidEmail === true && (
                    <div className="alert alert-error shadow-lg px-2 py-2">
                      <p className="text-sm">
                        Please enter a valid email address.
                      </p>
                    </div>
                  )} */}
                </div>
                <div className="mb-4">
                  <input
                    ref={passwordInput}
                    type="password"
                    className={`w-full border outline-0 border-gray-600 `}
                  />
                  <label htmlFor="password">Password</label>
                  {/* {isValidPassword === true && (
                    <div className="alert alert-error shadow-lg px-2 py-2">
                      <p className="text-sm">
                        Password must be at least 8 characters long.
                      </p>
                    </div>
                  )} */}
                </div>
                <div className="mb-2">
                  <input type="checkbox" />
                  <label htmlFor="passwordRemembered">Remember Password</label>
                </div>
                <div>
                  <button
                    className="btn btn-primary w-full"
                    onClick={(e) => {
                      SignIn(e);
                    }}
                  >
                    Login
                  </button>
                </div>
                <hr className="my-4" />
                <div className="mb-4">
                  <p className="text-center">Don&apos;t have an account yet?</p>
                  <Link className="btn btn-secondary w-full" href="./signup">
                    Create an account here
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

export default LoginForm;
