import Head from 'next/head';
import Image from 'next/image';
import { Header, Footer } from '../../shared/component/index';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>WebPulse | Home Page</title>
      </Head>
      <Header />
      <div className="custom-background-vision" />
      <main className="mt-20">
        <section className="pb-[5rem], pt-[5rem] md:pt-[9rem]">
          <div className="mx-auto max-w-6xl px-3">
            <h1 className="w-full text-3xl md:text-5xl text-start md:text-center font-bold text-primary typo-playfair leading-[1.375rem]">
              Quick performance <span className="text-secondary">insight.</span>
            </h1>
            <p className="mb-10 md:mb-20 text-start md:text-center md:text-xl md:px-5 mmd:mx-auto text-slate-400 w-full">
              Performance insights generated by our system.
            </p>
            <div
              id="scanInput"
              className="flex justify-center items-center flex-col md:flex-row gap-1 md:gap-2"
            >
              <div className="relative shadow-md h-100 1-100 w-full md:w-auto">
                <p className="absolute inset-y-0 flex items-center pl-[0.75rem]">
                  https://
                </p>
                <input
                  id="inputURL"
                  autoComplete="none"
                  type="text"
                  placeholder="webpulse.com"
                  // class="ut-none-outline"

                  className="w-full pl-[4.9rem] pt-[0.28rem] pb-[0.28rem] md:w-auto"
                />
              </div>

              <button
                id="scanInsight"
                // class="btn ut-hover-opacity"
                className="text-white shadow-md w-full md:w-auto flex rounded-md bg-primary hover:bg-[#467989] px-4 py-[0.375rem]"
              >
                Run Test
              </button>
            </div>
          </div>
        </section>

        <section className="px-3 py-20 mx-auto max-w-6xl">
          <div className="flex flex-col md:flex-row w-full justify-around gap-4">
            <div>
              <h2 className="text-gray-600 font-bold text-xl md:text-2xl">
                Developer-friendly
              </h2>
              <p className="text-slate-500">
                Easy for Developers. Effortlessly assess website performance
                with ease using its user-friendly, intuitive design for
                developers.
              </p>
            </div>
            <div>
              <h2 className="text-gray-600 font-bold text-xl md:text-2xl">
                Automation
              </h2>
              <p className="text-slate-500">
                Automate Your Website Monitoring. Say goodbye to manual efforts
                and continuously monitor with WebPulse&apos;s automation.
              </p>
            </div>
            <div>
              <h2 className="text-gray-600 font-bold text-xl md:text-2xl">
                Public Api
              </h2>
              <p className="text-slate-500">
                Enhance Performance Monitoring. Utilize WebPulse&apos;s public
                API to monitor and maintain your website&apos;s performance.
              </p>
            </div>
          </div>
        </section>

        {/*  */}
        <section className="py-20 md:pt-9 mx-auto max-w-6xl px-3">
          <div className="flex flex-col justify-center items-center">
            <div className="w-full max-w-3xl text-center">
              <h2 className="mb-4 text-gray-600 font-bold text-xl md:text-2xl">
                Testimonials
              </h2>
              <p className="mb-4 pb-2 md:mb-5 md:pb-0">
                See what our satisfied users have to say about our webPulse!
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-10 md:gap-20 text-center">
            <div className="mb-5 md:mb-0">
              <div className="flex justify-center mb-4">
                <Image
                  src="/assets/bill.webp"
                  className="rounded-full shadow-md"
                  width="150"
                  height="150"
                  alt="testimonial_picture"
                />
              </div>
              <h3 className="mb-3 text-gray-600 font-bold text-xl md:text-2xl">
                Bill Ofrights
              </h3>
              <p className="text-primary mb-3">Web Developer</p>
              <p className="px-4 md:px-10">
                webPulse is a game-changer! It helped me identify and fix issues
                on my site, improving my user experience and ultimately boosting
                my business.
              </p>
            </div>
            <div className="mb-5 md:mb-0">
              <div className="flex justify-center mb-4">
                <Image
                  src="/assets/mark.webp"
                  className="rounded-full shadow-md"
                  width="150"
                  height="150"
                  alt="testimonial_picture"
                />
              </div>
              <h3 className="mb-3 text-gray-600 font-bold text-xl md:text-2xl">
                Marky Zuckerpunch
              </h3>
              <p className="text-primary mb-3">Digital Marketing Specialist</p>
              <p className="px-4 md:px-10">
                As a non-technical person, I was skeptical about using a website
                tester app, but this one exceeded my expectations. It was
                user-friendly and helped me detect issues that I would have
                never noticed on my own.
              </p>
            </div>
            <div className="mb-5 md:mb-0">
              <div className="flex justify-center mb-4">
                <Image
                  src="/assets/elon.webp"
                  className="rounded-full shadow-md"
                  width="150"
                  height="150"
                  alt="testimonial_picture"
                />
              </div>
              <h3 className="mb-3 text-gray-600 font-bold text-xl md:text-2xl">
                Ewlon Masks
              </h3>
              <p className="text-primary mb-3">UX Designer</p>
              <p className="px-4 md:px-10">
                I&apos;ve been using webPulse for a while now, and it has saved
                me countless hours of manual testing. The detailed reports and
                actionable insights have allowed me to make informed decisions
                and improve my website&apos;s performance.
              </p>
            </div>
          </div>
        </section>

        {/*  */}
        <section className="mx-auto max-w-6xl px-3 py-20">
          <blockquote className="custom-blockquote-border">
            <p className="text-xl">
              WebPulse is a free platform designed by developers to offer quick
              insights into your website&apos;s performance with an intuitive
              interface and powerful automation features. While we can&apos;t
              provide specific advice on improving your metrics, we&apos;ll
              direct you to other resources to optimize your website. Our
              platform makes it easy to monitor and track your metrics, allowing
              you to see a clear picture of your website&apos;s performance. Say
              goodbye to manual monitoring efforts and use our public API to
              enhance your website&apos;s metrics monitoring.
            </p>
          </blockquote>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Home;
